{{- if not .Values.splunk.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-agent.fullname" . }}-splunk
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPLUNK_ACCESS_TOKEN: {{ .Values.splunk.accessToken | quote }}
{{- end }}
---
{{- if not .Values.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-agent.fullname" . }}-aws
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
{{- end }}
