"""
Fine-tune a local model (qwen2.5:14b or similar) on o11y agent training data.

Uses Unsloth for 4-bit LoRA fine-tuning — runs on a single 24 GB GPU.
Input:  training/data/train.jsonl  (generated by generate_from_assessments.py)
Output: training/output/           (LoRA adapter + merged model)

Requirements:
    pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    pip install trl datasets

Usage:
    # Generate training data first
    python3 training/generate_from_assessments.py

    # Then fine-tune
    python3 training/finetune.py
    python3 training/finetune.py --model Qwen/Qwen2.5-14B-Instruct --epochs 3
"""

import argparse
import pathlib
import sys

TRAIN_JSONL = pathlib.Path(__file__).parent / "data" / "train.jsonl"
OUTPUT_DIR  = pathlib.Path(__file__).parent / "output"

DEFAULT_MODEL  = "Qwen/Qwen2.5-14B-Instruct"
MAX_SEQ_LEN    = 4096
LORA_RANK      = 32


def load_dataset():
    from datasets import Dataset
    import json

    if not TRAIN_JSONL.exists():
        sys.exit(f"Training data not found: {TRAIN_JSONL}\nRun: python3 training/generate_from_assessments.py")

    rows = []
    with TRAIN_JSONL.open() as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))

    print(f"Loaded {len(rows)} training examples from {TRAIN_JSONL}")
    return Dataset.from_list(rows)


def apply_chat_template(examples, tokenizer):
    """Convert messages list → tokenizer chat template string."""
    texts = [
        tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=False)
        for msgs in examples["messages"]
    ]
    return {"text": texts}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model",   default=DEFAULT_MODEL,
                        help="HuggingFace model ID to fine-tune")
    parser.add_argument("--epochs",  type=int, default=3)
    parser.add_argument("--batch",   type=int, default=2,  help="Per-device train batch size")
    parser.add_argument("--grad-accum", type=int, default=4)
    parser.add_argument("--lr",      type=float, default=2e-4)
    parser.add_argument("--output",  default=str(OUTPUT_DIR))
    args = parser.parse_args()

    try:
        from unsloth import FastLanguageModel
        from trl import SFTTrainer, SFTConfig
    except ImportError:
        sys.exit(
            "Unsloth / TRL not installed.\n"
            "pip install 'unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git' trl datasets"
        )

    output_dir = pathlib.Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ----- Load base model with 4-bit quantization -----
    print(f"Loading {args.model} (4-bit)...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.model,
        max_seq_length=MAX_SEQ_LEN,
        load_in_4bit=True,
    )

    # ----- Attach LoRA adapter -----
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=LORA_RANK,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=42,
    )

    # ----- Dataset -----
    dataset = load_dataset()
    dataset = dataset.map(
        lambda ex: apply_chat_template(ex, tokenizer),
        batched=True,
        remove_columns=dataset.column_names,
    )
    # 90/10 train/eval split
    split = dataset.train_test_split(test_size=0.1, seed=42)

    # ----- Train -----
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=split["train"],
        eval_dataset=split["test"],
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LEN,
        args=SFTConfig(
            output_dir=str(output_dir / "checkpoints"),
            num_train_epochs=args.epochs,
            per_device_train_batch_size=args.batch,
            gradient_accumulation_steps=args.grad_accum,
            learning_rate=args.lr,
            warmup_ratio=0.05,
            lr_scheduler_type="cosine",
            fp16=True,
            logging_steps=10,
            eval_strategy="epoch",
            save_strategy="epoch",
            load_best_model_at_end=True,
            report_to="none",
        ),
    )

    print("Starting fine-tuning...")
    trainer.train()

    # ----- Save LoRA adapter -----
    adapter_dir = output_dir / "lora-adapter"
    model.save_pretrained(str(adapter_dir))
    tokenizer.save_pretrained(str(adapter_dir))
    print(f"LoRA adapter saved → {adapter_dir}")

    # ----- Optionally merge + export to GGUF for Ollama -----
    merge = input("\nMerge adapter into full model and export to GGUF? [y/N] ").strip().lower()
    if merge == "y":
        merged_dir = output_dir / "merged"
        print(f"Merging → {merged_dir} ...")
        model.save_pretrained_merged(str(merged_dir), tokenizer, save_method="merged_16bit")

        gguf_path = output_dir / "o11y-agent.gguf"
        print(f"Exporting GGUF → {gguf_path} ...")
        model.save_pretrained_gguf(str(gguf_path), tokenizer, quantization_method="q4_k_m")
        print(f"\nGGUF ready: {gguf_path}")
        print("To load in Ollama:")
        print(f"  ollama create o11y-agent -f <Modelfile>")
        print("  (Modelfile: FROM ./o11y-agent.gguf)")


if __name__ == "__main__":
    main()
